### PR TITLE
Added sevral supported printers to brlaser

### PR DESCRIPTION
**Pull request by QORTEC**
Since I had some extra time I decided to help out adding the supported printers to brlaser.

#66 DCP-L2510D
#87 DCP-L2537DW
#63 HL-2130
#90 HL-L2380DW
#77 MFC-7340
#50 MFC-8710DW
#83 MFC-L3750CDW

### CODE REVIEW

**Comment by jakubgs** [comment]
Any news on this?

**Comment by QORTEC** [comment]
At it again;


**Printers Definitions Added**:
#98  DCP-T500W
#88 DCP-T710W
#94  HL-5040
#101 HL-2250DN
#112 HL-L2305
#109 MFC-1810
#115 MFC-7320
#114 MFC-L2700DN

**Errors Fixed**:


HL-L2380DW
- removed ``Resolution k 1 0 0 0 "300dpi/300 DPI"`` since printer support is unknown
- added ``Duplex rotated`` since its a duplex printer

MFC-7340
- removed ``Duplex rotated`` since its not a duplex printer

HL-2130
- removed ``Duplex rotated`` since its not a duplex printer

**Comment by QORTEC** [comment]
**Printers Definitions Added**:
#102 DCP-L2550DW
#108 HL-L2310D
#103 HL-L2350DW
#57  MFC-L2750DW
#110 MFC-T910DW

**Errors Fixed**:

Moved HL-L2305 definition to correct position
 - from after HL-L2320D
 - to before  HL-L2310D

**Comment by Rapti** [comment]
I can confirm that this fork works with my MFC-7320 on a Raspberry Pi 2B.

**Comment by uranuspucksaxophone** [comment]
DCP-1612W also works...

**Comment by zeroheure** [comment]
@QORTEC I've wrote to  @pdewacht requesting to have a look. May be you could ask him to co-maintained this driver ?

**Comment by QORTEC** [comment]
@zeroheure 
If it would helpful for @pdewacht, I would be happy to occasionally go through and add driver definitions, it's a simple straightforward process.

Unfortunately that would be the limit of my help, since I don't know c++...

**Comment by zeroheure** [comment]
I can help on that too. That's why I wrote the wiki page. I don't know C++ neither.
Didn't get answer from @pdewacht yet.

**Comment by QORTEC** [comment]
I just started to look at the pull request in detail.
Closing this pull request until it is fixed.

**Comment by QORTEC** [comment]
Everything should be good to go

**Comment by QORTEC** [comment]
Removed unsupported printers form pull request (Inkjet):
#98  DCP-T500W
#88  DCP-T710W
#110 MFC-T910DW

Corrected ppd file names from earlier in pull request:
 - DCP-L2537DW
 - DCP-L2550DW
 - HL-L2350DW
 - MFC-L2700DN
 - MFC-L2750DW

Follow the standard naming convention for ModelName:
 - HL-2250DN
 - HL-2250DN
 - MFC-L2750DW
 - MFC-L3750CDW

Printers Definitions Added:
#141 Brother DCP-7020
#147 Brother HL-2230
#121 Brother HL-2240D
#128 Brother HL-2280DW
#144 Brother MFC-7440N
#129 Brother MFC-8860DN
#134 Brother MFC-L2700DW
#130 Brother MFC-L2710DN
#142 Lenovo LJ2650DN

I used the `ln` prefix for the Lenovo `.ppd` file since there was no predefined prefix.

> "Lenovo" is a portmanteau of "Le-" (from Legend) and "novo", Latin ablative for "new". 
[Wikipedia](https://en.wikipedia.org/wiki/Lenovo)

**Comment by QORTEC** [comment]
Added FujiXerox DocuPrint P265 dw (#150)

There's something especially satisfying to see other printer brands work with the driver, and I'm not really that involved in the project.

**Comment by QORTEC** [comment]
@uranuspucksaxophone Thanks for letting us know that `DCP-1612W` works!

Could you please connect to your printer via USB and run the following command `sudo lpinfo --include-schemes usb -l -v`? Then it will be possible to add a proper entry for your printer.

**Comment by uranuspucksaxophone** [comment]
> @uranuspucksaxophone Thanks for letting us know that `DCP-1612W` works!
> 
> Could you please connect to your printer via USB and run the following command `sudo lpinfo --include-schemes usb -l -v`? Then it will be possible to add a proper entry for your printer.

I'm afraid that the output of that command contains my printer serial number, which I will not share openly on the internet. I am sorry.

**Comment by uranuspucksaxophone** [comment]
In any case, This project is no longer being maintained so...

**Comment by QORTEC** [comment]
@uranuspucksaxophone we don't need the printers serial number, most people tend to remove it or `X` it out.
Really we only need the lines of output starting with `make-and-model = ` & `device-id = `, both of which are generic to the model of printer itself.

**Comment by QORTEC** [comment]
This project really only had one maintainer @pdewacht, who sadly hasn't been active on GitHub for just over a year now. The brlaser driver itself seems solid, though annoyingly there is a bug-fix in master that didn't make it into the v6 release.

I'm basically keeping the printer definitions updated, mainly for convenience of future updates
- if @pdewacht returns he can quickly tag a new release (without having to spend the time manually add 25+ printers)
- if someone else decides to officially develop/maintain the project, then the simple maintenance level issues are already completed

I've also just started tagging releases on my fork of brlaser, making it easier to keep track of the printers I've added or future updates. (Package maintainers will probably end up using a similar/my fork if no one ends up "maintaining" the project.)

That being said, I will accept PRs into my fork that related to adding/fixing printer definitions.

**Comment by uranuspucksaxophone** [comment]
```
Device: uri = usb://Brother/DCP-1610W%20series?serial=???
        class = direct
        info = Brother DCP-1610W series
        make-and-model = Brother DCP-1610W series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:DCP-1610W series;CLS:PRINTER;CID:Brother Laser Type1;
        location:
```

**Comment by axelsommerfeldt** [comment]
> (Package maintainers will probably end up using a similar/my fork if no one ends up "maintaining" the project.)

The official Fedora package is based on your fork:
```
Name         : printer-driver-brlaser
Version      : 6
Release      : 3.20220509git7716c7d.fc37
Repository   : fedora
Summary      : Brother laser printer driver
URL          : https://github.com/ondrejbudai/brlaser
```

It's a pity that @pdewacht is not responding, personally I would prefer a continuation of the original project (including you as co-maintainer).

**Comment by zeroheure** [comment]
I think we should collectively take this project, under an organisation umbrella (may be OpenPrinting ?). This will help to collect the works and will keep it running in case everyone disappear.

**Comment by QORTEC** [comment]
I'll update my fork soon as I have time again, probably end of December early January.

**Comment by QORTEC** [comment]
I'll also be looking into creating branches and pull in some pull requests from the master (here). 
Those who have pull requests feel free to submit a copy to me as well.

Though I will probably be conservative on accepting code changes, since I done know the language well enough to judge code quality.
If there anyone who wants to help maintain the code side of the project that would be appreciated.

**Comment by zeroheure** [comment]
I've sent an email to Til Kampeeter of OpenPrinting asking for help or ideas.

**Comment by zeroheure** [comment]
Here's the answer from Till Kampeeter

>I have written an e-mail to Peter de Wachter now. I hope that he will answer to me as the official printing guru.
>
>I have suggested him to transfer brlaser to OpenPrinting. I f he answers and I succeed, it will be simple for you. You post pull requests and I will handle them. If all works fine with your changed I will also give you direct push access

**Comment by QORTEC** [comment]
Thanks for keeping us updated. It would definitely be nice to have the changes merged and issues closed.

Fork wise I'll probably tag a release sometime tomorrow or the day after, there weren't many changes this time.

**Comment by axelsommerfeldt** [comment]
> Though I will probably be conservative on accepting code changes, since I done know the language well enough to judge code quality. If there anyone who wants to help maintain the code side of the project that would be appreciated.

I could do that. (I'm a professional C/C++ software developer since 1995, and I'm maintaining several LaTeX packages since 1994, currently on GitLab. BUT: I have absolutely no knowledge of writing CUPS drivers yet. So I would not be the best choice for this job.)

Furthermore I would like to comment the sources (using doxygen syntax) since there are only 6 comments (not counting the copyright header) in the complete project C++ files.

**Comment by QORTEC** [comment]
> > Though I will probably be conservative on accepting code changes, since I done know the language well enough to judge code quality. If there anyone who wants to help maintain the code side of the project that would be appreciated.
> 
> I could do that. (I'm a professional C/C++ software developer since 1995, and I'm maintaining several LaTeX packages since 1994, currently on GitLab. BUT: I have absolutely no knowledge of writing CUPS drivers yet. So I would not be the best choice for this job.)

Thank you any amount of help would be greatly appreciated.

> Furthermore I would like to comment the sources (using doxygen syntax) since there are only 6 comments (not counting the copyright header) in the complete project C++ files.

That will definitely help in the long run, thanks again.

Unless poked, I tend to only check back every 2-6 months to respond to issues and add printer definitions. Let me know when there are changes that I should pull in...

**Comment by QORTEC** [comment]
Merry Christmas/Happy Holidays;
I just found the time to create a new [release](https://github.com/QORTEC/brlaser/releases).

Notable additions/changes since last the summery;

**Printers Definitions Added**:
#107 Brother DCP-7070DW (Pull Request)
#172 Brother DCP-8065DN
#156 Brother HL-L5000D series
#162 Brother HL-L2370DN series

**Errors Fixed**:
#133 Fixed PCFileName ``br7365dn.ppd`` > ``br7460dn.ppd`` for MFC-7460DN. (Pull Request)

**Changed Code**:
#169 Explicitly disabled duplex using standard PCL code. (Pull Request)

**Issues Resolved**:
#169 Fixing the issue where printer ``HL-L2350DW`` continued to duplex even when disabled, however every other page was garbled. (Pull Request)

**Comment by QORTEC** [comment]
Closing this in favour of pull requests #179 and #180

Pull request #179 based off of the [definitions](https://github.com/Owl-Maintain/brlaser/tree/definitions) branch, which focuses on adding printer entries to the driver. This pull request (#92) focuses on adding printer entries to the driver.
Given the nature of the changes made, @pdewacht should be able to promptly accept this pull request.

Pull request #180 based off of the [code](https://github.com/Owl-Maintain/brlaser/tree/code) branch, which focuses changes to the codebase. This includes #169, with QORTEC#2 later expanding its functionality to explicitly set simplex, duplex no tumble, and duplex tumble modes
Due to the nature of the changes, @pdewacht will likely want to verify that the code works as expected and doesn't cause any issues

Moving forward, I'll be abandoning **QORTEC/brlaser** if favour of **Owl-Maintain/brlaser**. The Owl-Maintain fork is virtually identical to this pull request, with the only difference being an updated `README.md` and `Github Issues Templates` on the [master](https://github.com/Owl-Maintain/brlaser) branch.

**Pull request closed without merging**
