### PR TITLE
Add documentation how to install under Ubuntu

### PR DESCRIPTION
**Pull request by blob79**
Not much of a install documentation, but at least enough pointers to get started building and installing.

### CODE REVIEW

**Comment by timofonic** [comment]
@gnunicode Thanks for the thumbs up!

@blob79 Thanks for your effort!

@pdewacht Any news? Are you alive?

**Comment by pdewacht** [comment]
I'm planning on switching to cmake (see the 'cmake' branch), so I'm not going to merge this.

But is there a reason the Ubuntu printer-driver-brlaser package is not working for you?

**Comment by blob79** [comment]
I think LTS Ubuntu doesn't ship with the driver. The driver that is
included doesn't support duplex.

Cheers
Thomas

**Comment by pdewacht** [comment]
OK that makes sense.

**Pull request merged**
