### PR TITLE
Package available on guix, too

### PR DESCRIPTION
**Pull request by nico202**
Available here http://guix.gnu.org/packages/brlaser-4-1.779f71e/

### CODE REVIEW

**Comment by pdewacht** [comment]
That's an old version though. Are you involved in Guix? Can you ask them to update the package?

**Comment by nico202** [comment]
Yeah I'm involved, I'll send a patch to them with v6, thanks!

**Comment by nico202** [comment]
Here we go
https://git.savannah.gnu.org/gitweb/?p=guix.git;a=commit;h=711e8bf75fdacc8218b3957bbd7cb367da6392b5

**Comment by pdewacht** [comment]
Thanks!

**Pull request merged**
